Round gridspec tilesize to fix floating point precision issue
opendatacube/odc-geo pull request #180
Opened 2024-09-26 05:18 UTC by alexgleith

Fixes an issue where small resolutions (i.e., `0.003`) would lead to crazy coordinates in geoboxes for a gridspec, due to floating point issues.

Test included.

2024-09-30 05:44 UTC, Kirill888 commented
Why?

2024-09-30 05:54 UTC, alexgleith commented
>Why?

Why the PR?

See the test output without the fix.

2024-10-01 00:46 UTC, Kirill888 requested changes
The proposed solution is not a robust one. Issue it’s trying to solve is not explained in the pr and it feels like the real problem is some place else. Version updates are typically done as a separate commit in this repo

2024-10-01 00:50 UTC, alexgleith commented
>The proposed solution is not a robust one. 

I agree. Not sure if there's a better approach, though.

>feels like the real problem is some place else

I looked through the code and debugged pretty deep. This is where the problem is caused.

>Issue it’s trying to solve is not explained in the pr

Ok, I'll explain it. Apologies...

>Version updates are typically done as a separate commit in this repo

Ok, I'll remove the version update.

2024-10-01 01:00 UTC, alexgleith commented
Text updated to explain the reasoning @Kirill888.

2024-10-01 01:14 UTC, Kirill888 commented
Unrelated build fixes should be a separate commit.
There is a robust way of rounding affine matrix already
https://odc-geo.readthedocs.io/en/latest/_api/odc.geo.math.snap_affine.html#odc.geo.math.snap_affine

We can it just keep adding rounding in random places to support specific issues caused by use of EPSG 4326

2024-10-01 02:02 UTC, omad commented
> Text updated to explain the reasoning @Kirill888.

Is there an actual problem, other than that the numbers look funny?

2024-10-01 02:49 UTC, alexgleith commented
>Is there an actual problem, other than that the numbers look funny?

Yeah, the gridspec drives the input and output grid for an analysis, so the coordinates of the geotiff that's being produced will be screwy too.

2024-10-01 02:52 UTC, alexgleith commented
>There is a robust way of rounding affine matrix already

But the fundamental issue is not the affine, it's the GridSpec, which is producing bad GeoBoxes with bad Affines.

And the bad GridSpec is caused by the incorrect rounding on the tile size. It could be fixed after the fact, but that feels like hiding the underlying problem, to me.

>Unrelated build fixes should be a separate commit.

Ok, fair. I can split that noise out.

2024-10-14 22:28 UTC, alexgleith commented
So, is there a better way to do this? I'd really like to not need to maintain my own function for creating a gridspec because we can't handle digital numbers here.

This sucks!

![image](https://github.com/user-attachments/assets/d146084d-203f-4ef0-ab26-5766467ea0d6)

2025-02-26 22:05 UTC, alexgleith commented
Closing. I resolved this using [GeoboxTiles](https://odc-geo.readthedocs.io/en/latest/api.html#geoboxtiles) instead.

I still think this is uncontroversial, but I've moved on!

2025-02-26 22:05 UTC, closed without merging